version: "3.8"
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:starter
    hostname: "`api.${DOMAIN}`"
    container_name: medusa-server-default
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
      REDIS_URL: redis://redis
      NODE_ENV: development
      PORT: 9000
    env_file:
      - ./.env
    ports:
      - "9000:9000"
    volumes:
      - .:/app/medusa
      - node_modules:/app/medusa/node_modules
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.backend.rule=Host(`api.${DOMAIN}`)
      - traefik.http.routers.backend.entrypoints=https
      # - traefik.http.routers.backend.tls=true
      - traefik.http.routers.backend.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.services.backend.loadbalancer.server.port=9000
    networks:
      - traefik
      - medusa_internal

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    networks:
      - medusa_internal
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker

  redis:
    image: redis
    expose:
      - 6379
    networks:
      - medusa_internal

volumes:
  node_modules:

networks:
  traefik:
    name: traefik
  medusa_internal:
    internal: true