version: "3.8"
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:starter
    hostname: "`api.${DOMAIN}`"
    container_name: medusa-server-default
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
      REDIS_URL: redis://redis
      NODE_ENV: development
      PORT: 9000
    env_file:
      - ./.env
    ports:
      - "9000:9000"
    volumes:
      - .:/app/medusa
      - node_modules:/app/medusa/node_modules
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.services.backend.loadbalancer.server.port=9000
      - traefik.http.routers.backend.rule=Host(`api.${DOMAIN}`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls.certresolver=${CERT_RESOLVER}
      # - traefik.http.routers.backend.tls=true      
    networks:
      - traefik
      - medusa_internal

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    networks:
      - medusa_internal
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker
    volumes: 
      - db:/var/lib/postgresql/data

  redis:
    image: redis
    expose:
      - 6379
    networks:
      - medusa_internal

  meilisearch:
    image: getmeili/meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_NO_SENTRY=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - meilisearch_data:/data.ms
    networks:
      - traefik
    labels:
      - traefik.docker.network=traefik
      - traefik.enable=true
      - traefik.http.routers.search.entrypoints=websecure
      - traefik.http.routers.search.rule=Host(`search.${DOMAIN}`)
      - traefik.http.routers.search.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.services.search.loadbalancer.server.port=7700

volumes:
  db:
    driver: local
  node_modules:
  meilisearch_data:

networks:
  traefik:
    name: traefik
  medusa_internal:
    internal: true